name: IAM Roles Setup

on:
  push:
    branches:
      - main

jobs:
  create_iam_roles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.1

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/iam-roles-setup

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform/iam-roles-setup

      - name: Set Outputs and Trigger Dispatch
        id: trigger-dispatch
        run: |
          echo "::set-output name=eks_node_group_role_arn::$(terraform output -raw eks_node_group_role_arn)"
          echo "::set-output name=github_actions_role_arn::$(terraform output -raw github_actions_role_arn)"
      
      - name: Trigger EKS Deploy Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          event-type: eks-deploy
          client-payload: |
            {
              "eks_node_group_role_arn": "${{ steps.trigger-dispatch.outputs.eks_node_group_role_arn }}",
              "github_actions_role_arn": "${{ steps.trigger-dispatch.outputs.github_actions_role_arn }}"
            }