name: IAM Roles Setup

on:
  push:
    branches:
      - main

jobs:
  create_iam_roles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.1

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/iam-roles-setup

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform/iam-roles-setup

      - name: Save Outputs
        id: save_outputs
        run: |
          echo "eks_node_group_role_arn=$(terraform output -raw eks_node_group_role_arn)" >> eks_node_group_role_arn.txt
          echo "github_actions_role_arn=$(terraform output -raw github_actions_role_arn)" >> github_actions_role_arn.txt
        working-directory: ./terraform/iam-roles-setup

      - name: Upload Outputs Artifact
        uses: actions/upload-artifact@v3
        with:
          name: iam-role-arns
          path: |
            eks_node_group_role_arn.txt
            github_actions_role_arn.txt